name: Compiling and Testing

on: [push]

jobs:
  compile_and_run:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile program
        run: make all

      - name: Run on localhost
        run: |
          ./webserv &
          sleep 2

      - name: Curl Test
        run: |
          curl -s --fail http://127.0.0.1:8080 || (echo "Server not responding" && exit 1)
    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests 

      - name: Init Tests
        run: bash init_test.sh

      - name: Server Test 
        run: python3 server_test.py

      - name: Locations Test
        run: python3 locations_test.py
