name: Compiling Test

on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile program
        run: make all

      - name: Run on localhost
        run: |
          ./webserv &  # Run in background
          sleep 2      # Wait for server to start

      - name: Curl Test
        run: |
          curl -s --fail http://127.0.0.1:8080 || (echo "Server not responding" && exit 1)
